<?php

// $Id: videojs.module,v 1.1.2.2 2010/10/31 12:43:03 heshanmw Exp $

/**
 * @file
 * Provides an HTML5-compatible with Flash-fallback video player.
 *
 * This module provides functionality for loading the videojs library and
 * formatters for CCK FileFields.
 */

/**
 * Implementation of hook_menu().
 */
function videojs_menu() {
  $items = array();

  $items['admin/settings/videojs'] = array(
    'title' => 'VideoJS Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('videojs_settings_form'),
    'access arguments' => array('administer site configuration'),
    'description' => 'Configure the settings for the VideoJS module.',
    'file' => 'includes/videojs.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function videojs_theme() {
  return array(
    'videojs_formatter_videojs' => array(
      'arguments' => array('element' => NULL),
      'template' => 'theme/videojs',
      'file' => 'includes/videojs.theme.inc',
    ),
    'videojs_view' => array(
      'arguments' => array('view' => NULL, 'items' => NULL),
      'template' => 'theme/videojs',
      'file' => 'includes/videojs.theme.inc',
    ),
  );
}

/**
 * Implementation of Views' hook_views_api().
 */
function videojs_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'videojs') . '/includes',
  );
}

/**
 * Implementation of CCK's hook_field_formatter_info().
 */
function videojs_field_formatter_info() {
  return array(
    'videojs' => array(
      'label' => t('VideoJS : HTML5 Video Player'),
      'field types' => array('filefield', 'uploadfield'),
      'multiple values' => CONTENT_HANDLE_MULTIPLE,
      'description' => t('Display a video file as an HTML5-compatible with Flash-fallback video player.'),
    )
  );
}

/**
 * Add the videojs library to the page.
 *
 * @param $add
 *   By default this function will add videojs to the page JavaScript array
 *   directly. If wanting to store the videojs file as an #attached property,
 *   set this to FALSE and videojs_add() will only return the needed array
 *   suitable for use as an #attached property.
 */
function videojs_add($add = TRUE) {
  static $added = FALSE;

  $directory = variable_get('videojs_directory', 'sites/all/libraries/video-js');
  $return = FALSE;
  if (file_exists($directory . '/video.js')) {
    $filepath = $directory . '/video.js';
    $filepath_css = $directory . '/video-js.css';
  }

  if (isset($filepath)) {
    $videojs_js = drupal_get_path('module', 'videojs') . '/theme/videojs.js';
    $videojs_css = drupal_get_path('module', 'videojs') . '/theme/videojs.css';
    $settings = array('videojs' => array(
        'swfPath' => base_path() . variable_get('videojs_directory', 'sites/all/libraries/video-js'),
        'autoPlay' => (int) variable_get('videojs_autoplay', ''),
        ));
    if ($add) {
      drupal_add_js($filepath);
      drupal_add_css($filepath_css);
      drupal_add_js($videojs_js);
      drupal_add_css($videojs_css);
      if (!$added) {
        drupal_add_js($settings, 'setting');
        $added = TRUE;
      }
    }
    $return = array(
      'js' => array(
        array('data' => $filepath),
        array('data' => $videojs_js),
        array('data' => $settings, 'type' => 'setting'),
      ),
      'css' => array(
        array('data' => $filepath_css),
        array('data' => $videojs_css),
      ),
    );
  }

  return $return;
}

/**
 * Return the version of video JS installed.
 *
 * @param $directory
 *   The directory to check for a videojs installation.
 */
function videojs_get_version($directory = NULL) {
  $version = 0;

  if (!isset($directory)) {
    $directory = variable_get('videojs_directory', 'sites/all/libraries/video-js');
  }

  if (file_exists($directory . '/video.js')) {
    $contents = file_get_contents($directory . '/video.js');
  }
  else
    return FALSE;

  $matches = array();
  preg_match('/v.?[ ]*([\d.]+)/i', $contents, $matches);

  if (isset($matches[0])) {
    $version = substr($matches[0], 1);
  }

  return $version;
}
